@startuml
left to right direction
skinparam packageStyle rectangle
actor User
actor Admin
actor Buyer
actor Seller
rectangle "Used electronics marketplace" {
    User --> (Sign In)
    User --> (Sign Up)
    User --> (View product)
    User --> (Search product)
    (Create post) ..> (Post management): Extend
    (Update post) ..> (Post management): Extend
    (Delete post) ..> (Post management): Extend
    (Approve post) ..> (Post management): Extend
    (Reject post) ..> (Post management): Extend
    (Chat with seller) ..> (View product): Extend
    (Place order) ..> (View product): Extend
    User --> (Create post)
    User --> (Update post)
    User --> (Delete post)
    Admin --> (Approve post)
    Admin --> (Reject post)
    (Approve order) ..> (Order management): Extend
    (Reject order) ..> (Order management): Extend
    (Track order status) ..> (Order management): Extend
    Seller --> (Order management)
    User --> (Track order status)
    Buyer --> (Confirm delivery of order)
    (Rate seller) ..> (Confirm delivery of order): Extend
    Seller --> (Confirm order)
    (Confirm delivery of order) ..> (Confirm order): Include
}
rectangle "Administration system"{
    Admin --> (Sign in as administrator)
}

Buyer --|> User
Seller --|> User

@enduml
