@startuml
|User <<Seller>>|
|User|
start
floating note left
Assuming the user is logged in
and in post details page
end note
:(1) Click "Chat with seller" button;
|System|
:(2) Navigate user to chat page;
|User|
repeat
   :(3) Send message;
   |User <<Seller>>|
   :(4) Receive message;
backward:Send message;
|User|
backward:(7) Reiceve message;
|User <<Seller>>|
repeat while ((5) want to chat?) is (yes)
-> no;
stop
@enduml