@startuml
|Seller|User <<Seller>>
|System|
|Buyer|User <<Buyer>>

|Seller|
start
floating note left
Assuming the seller is logged in
and navigate to order management page
end note

:(1) Select a order to view;
:(2) Click "Confirm" button;
|System|
:(3) Display confirm modal;
|Seller|
if ((6) confirm) then (yes)
   |System|
   :(7) Confirm the order;
   :(8) Notification "Confirm order successfully";
   :(9) Send a message to notify;
   |Buyer|
   :(10) Receive a message;
   stop
|Seller|
else (no) 
stop
endif


@enduml