@startuml
|User|
start
floating note left
Assuming the user is logged in 
and goes to the correct post 
they want to delete
end note
:(1) Request to delete the post;
|System|
:(2) Display confirm modal;
|User|
:(3) Confirm delete;
|System|
if ((4) Post exists in system) then (Yes)
:(5) Delete the post;
:(6) Show success message;
else (no)
:(7) Show error message;
endif
stop
@enduml