@startuml
|User|
start
floating note left
Assuming the user is not logged in
and in sign in page
end note
:(1) Click on 'Forgot password' button;
|System|
:(2) Redirect to 'Reset password' page;
|User|
repeat
  :(3) Enter email or phone number;
|System|
repeat while ((4) valid email or phone number?) is (no)
->yes;
:(5) Generate the verification link;
:(6) Send the link to user;
|User|
:(7) Click on the verification link;
|System|
if ((8) valid link) then (yes)
:(9) Redirect to the 'Change password' page;
else (no)
:(10) Notification 'Invalid verification link';
stop;
endif
|User|
repeat
  :(11) Enter new password;
|System|
repeat while ((12) valid new password?) is (no)
->yes;
:(13) Change password;
:(14) Redirect to sign in page;
stop
@enduml
