@startuml
|User|
start
floating note left
Assuming the user is logged in 
and navigates to the post consist of
the product they want to place
end note

:Click "Buy now";
|System|
:Navigate to Check out screen;
:Request user to fill out 
all of order information;
|User|
:Enter address, consignee information,
select payment method;
:Click check out button;
|System|
switch (check payment method) 
case (pay online)
      :Request user 
to make a payment;
      |User|
      while (Carry out the payment process) is (yes) 
         note left
         business process for 
         this action will be added soon 
         end note
         |System|
         :Verify payment;
         if (success) then (yes)
         :Notification "Payment successful";
         :Save order;
         stop
         else (no)
            :Notification "Payment failed";
         endif
      |User|
      endwhile (no)
         stop
|System|
case (payment on delivery)
endswitch
:Save order;
stop
@enduml