@startuml
|User|
start
repeat 
:(1) Enter sign in details;
|System|
:(2) Send these information
to User controller;
backward:(4) Notification "Username or password is incorrect";
repeat while ((3) data is valid) is (no) not (yes)
:(5) Notification "Logged in successfully";
:(6) Redirect the user to Home page;
stop
@enduml