@startuml
|User|
start
repeat 
:(1) Enter sign up details;
|System|
:(2) Send these information
to User controller;
backward:(4) Notification "Phone/email is already exist";
repeat while ((3) validate data (is email valid?, is phone or email exist? ,...)) is (no) not (yes)
:(4) Notification "Successfully registration";
:(5) Redirect the user to Home page;
stop
@enduml