@startuml
|Admin|
|System| Administration system

|Admin|
start
floating note left
Assuming the admin is in
the administrator sign in page.
end note
repeat 
:(1) Enter sign in details;
|System|
backward:(2) Notification "Username or password is incorrect";
repeat while ((3) valid data) is (no) not (yes)
:(4) Notification "Logged in successfully";
:(5) Redirect the admin to Administration page;
stop
@enduml