@startuml
|User|
start
floating note left
Assuming the user is logged in 
and goes to the correct post 
they want to update
end note
:(1) Request to update the post;
|System|
:(2) Display edit screen;
|User|
:(3) Change some information;
:(4) Click save button;
|System|
if ((5) Input is valid) then (Yes)

'|System|
floating note right
"Wait" here can mean
set state of the post
is "pending"
end note
:(6) Save the post and wait
the administrator confirm;
:(7) Show success message;
else (no)
:(8) Show error message;
endif
stop
@enduml