@startuml
autonumber
actor Admin
boundary "Sign in page" as SignIn
control "User controller" as UserClr
boundary "Home Page" as Home
Admin -> SignIn++: Enter sign in details
SignIn -> UserClr++: Login user
UserClr -> UserClr: Validate data
alt successful case
UserClr -> SignIn: Success
SignIn -> Admin: Notification: Logged in successfully
else failed case
SignIn -> Admin: Username or password is incorrect
end
UserClr --
SignIn -> Home --: Redirect to Admin page
@enduml