@startuml
class User {
    -username: String
    -password: String
    -phoneNumber: String
    -email: String
    -rating: Int
    +verifySignIn()
    +createUser()
}

class Buyer {
    -purchaseOrders: List<Order>
    +confirmDeliveryOfOrder()
    +rateSeller()
}

class Seller {
    -salesOrders: List<Order>
    +confirmOrder()
}

class Admin {
    -username: String
    -password: String
    -phoneNumber: String
    -email: String
    +approvePost()
    +rejectPost()
    +approveOrder()
    +rejectOrder()
}

class Post {
    -user: User
    -images: List<String>
    -product: Product
    -price: BigDecimal
    -title: String
    -description: String
    -area: String
    -status: PostStatus
    +approvePost()
    +rejectPost()
}

enum PostStatus {
    CREATED,
    APPROVED,
    REJECTED
}

class Order {
    -post: Post
    -status: OrderStatus
    -createdDate: Date
    -total: BigDecimal
    -shipment: Shipment
    -payment: Payment
    +approveOrder()
    +rejectOrder()
    +cancelOrder()
    +trackOrder()
}

enum OrderStatus {
    CREATED,
    CONFIRMED,
    APPROVED,
    REJECTED,
    DELIVERING,
    COMPETED
}

class Payment {
    -order: Order
    -createdDate: Date
    -provider: String
    -status: PaymentStatus
    -method: PaymentMethod
    +updatePaymentStatus()
}

enum PaymentStatus {
    PENDING,
    PROCESSING,
    COMPETED,
    DECLINED,
    CANCELED,
    REFUNDED
}

enum PaymentMethod {
    DIRECT
    CREDIT_CARD
    BANKING
}

class Shipment {
    -order: Order
    -status: ShipmentStatus
    -cost: BigInteger
    -supplier: String
    -destination: String
    -pickupDate: Date
    -deliveryDate: Date
    +confirmDelivery()
}

enum ShipmentStatus {
    PENDING
    PICKED_UP
    IN_TRANSIT
    DELIVERED
}

class Category {
-name: String
-products: List<Product>
}

class Product {
-name: String
-description: String
-brand: String
-categories: List<Category>
}

class Rating {
-buyer: Buyer
-seller: Seller
-post: Post
-rating: Integer
-comment: String
}

User "1" *-- "*" Post
Product "1" *-- "*" Post
Seller "1" *-- "*" Rating
Category "*" *-- "*" Product
Post "1" o-- "1" Order
Order "1" *-- "1" Payment
Order "1" *-- "1" Shipment
User <|-- Buyer
User <|-- Seller

@enduml